// <auto-generated />
using System;
using IMS.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IMS.DAL.Migrations
{
    [DbContext(typeof(IMSContext))]
    [Migration("20250108195653_AddcorrectedItemSeedData")]
    partial class AddcorrectedItemSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IMS.DAL.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("IMS.DAL.Entities.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MinimumStockQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ItemID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2025, 1, 7, 19, 56, 53, 10, DateTimeKind.Utc).AddTicks(808),
                            Description = "Test item with low stock",
                            ExpiryDate = new DateTime(2025, 1, 13, 19, 56, 53, 10, DateTimeKind.Utc).AddTicks(547),
                            ItemName = "Low Stock Item 1",
                            MinimumStockQuantity = 10,
                            Price = 10.99m,
                            StockQuantity = 5,
                            Unit = "pcs"
                        },
                        new
                        {
                            ItemID = 2,
                            Category = "Office Supplies",
                            CreatedAt = new DateTime(2025, 1, 8, 17, 56, 53, 10, DateTimeKind.Utc).AddTicks(1000),
                            Description = "Recently added item",
                            ExpiryDate = new DateTime(2025, 2, 7, 19, 56, 53, 10, DateTimeKind.Utc).AddTicks(999),
                            ItemName = "New Item",
                            MinimumStockQuantity = 5,
                            Price = 15.99m,
                            StockQuantity = 20,
                            Unit = "pcs"
                        },
                        new
                        {
                            ItemID = 3,
                            Category = "Food",
                            CreatedAt = new DateTime(2024, 12, 29, 19, 56, 53, 10, DateTimeKind.Utc).AddTicks(1009),
                            Description = "Item near expiry",
                            ExpiryDate = new DateTime(2025, 1, 14, 19, 56, 53, 10, DateTimeKind.Utc).AddTicks(1008),
                            ItemName = "Expiring Item",
                            MinimumStockQuantity = 5,
                            Price = 25.99m,
                            StockQuantity = 15,
                            Unit = "boxes"
                        });
                });

            modelBuilder.Entity("IMS.DAL.Entities.ItemCategory", b =>
                {
                    b.Property<int>("ItemID")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryID")
                        .HasColumnType("integer");

                    b.HasKey("ItemID", "CategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("ItemCategories");
                });

            modelBuilder.Entity("IMS.DAL.Entities.Stock", b =>
                {
                    b.Property<int>("StockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockID"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemID")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("integer");

                    b.HasKey("StockID");

                    b.HasIndex("ItemID");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("IMS.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 8, 19, 56, 52, 911, DateTimeKind.Utc).AddTicks(2362),
                            Email = "admin@ims.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$bliERvaBkYNCMIAVPH6IZuh6xUvy9IxGF7j8X64MpyEAiw.o.QT3O",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 8, 19, 56, 53, 9, DateTimeKind.Utc).AddTicks(2653),
                            Email = "test@ims.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$tATI.jCkkYcz60dHrJ7pB.Gnr9csdsd5Suey6HkPnnd.p5qN0ZfES",
                            Role = "User",
                            Username = "testuser"
                        });
                });

            modelBuilder.Entity("IMS.DAL.Entities.ItemCategory", b =>
                {
                    b.HasOne("IMS.DAL.Entities.Category", "Category")
                        .WithMany("ItemCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMS.DAL.Entities.Item", "Item")
                        .WithMany("ItemCategories")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("IMS.DAL.Entities.Stock", b =>
                {
                    b.HasOne("IMS.DAL.Entities.Item", "Item")
                        .WithMany("Stocks")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("IMS.DAL.Entities.Category", b =>
                {
                    b.Navigation("ItemCategories");
                });

            modelBuilder.Entity("IMS.DAL.Entities.Item", b =>
                {
                    b.Navigation("ItemCategories");

                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
