// <auto-generated />
using System;
using IMS.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IMS.DAL.Migrations
{
    [DbContext(typeof(IMSContext))]
    [Migration("20250110161805_UpdateInventoryRepository")]
    partial class UpdateInventoryRepository
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IMS.DAL.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("IMS.DAL.Entities.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MinimumStockQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ItemID");

                    b.HasIndex("UserId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 12, 31, 16, 18, 5, 421, DateTimeKind.Utc).AddTicks(9854),
                            Description = "Admin item nearing expiry",
                            ExpiryDate = new DateTime(2025, 1, 15, 16, 18, 5, 421, DateTimeKind.Utc).AddTicks(9347),
                            ItemName = "Admin Near Expiry Item 1",
                            MinimumStockQuantity = 10,
                            Price = 20.99m,
                            StockQuantity = 15,
                            Unit = "pcs",
                            UserId = 1
                        },
                        new
                        {
                            ItemID = 2,
                            Category = "Office Supplies",
                            CreatedAt = new DateTime(2025, 1, 5, 16, 18, 5, 422, DateTimeKind.Utc).AddTicks(439),
                            Description = "Admin item with low stock",
                            ExpiryDate = new DateTime(2025, 2, 9, 16, 18, 5, 422, DateTimeKind.Utc).AddTicks(436),
                            ItemName = "Admin Low Stock Item 1",
                            MinimumStockQuantity = 10,
                            Price = 5.99m,
                            StockQuantity = 3,
                            Unit = "pcs",
                            UserId = 1
                        },
                        new
                        {
                            ItemID = 3,
                            Category = "Food",
                            CreatedAt = new DateTime(2025, 1, 3, 16, 18, 5, 422, DateTimeKind.Utc).AddTicks(441),
                            Description = "Admin item near expiry and low stock",
                            ExpiryDate = new DateTime(2025, 1, 14, 16, 18, 5, 422, DateTimeKind.Utc).AddTicks(440),
                            ItemName = "Admin Near Expiry & Low Stock Item",
                            MinimumStockQuantity = 5,
                            Price = 15.99m,
                            StockQuantity = 2,
                            Unit = "boxes",
                            UserId = 1
                        },
                        new
                        {
                            ItemID = 4,
                            Category = "Garden Supplies",
                            CreatedAt = new DateTime(2025, 1, 8, 16, 18, 5, 422, DateTimeKind.Utc).AddTicks(445),
                            Description = "Another admin item nearing expiry",
                            ExpiryDate = new DateTime(2025, 1, 16, 16, 18, 5, 422, DateTimeKind.Utc).AddTicks(442),
                            ItemName = "Admin Near Expiry Item 2",
                            MinimumStockQuantity = 10,
                            Price = 12.99m,
                            StockQuantity = 20,
                            Unit = "pcs",
                            UserId = 1
                        },
                        new
                        {
                            ItemID = 5,
                            Category = "Cleaning Supplies",
                            CreatedAt = new DateTime(2025, 1, 7, 16, 18, 5, 422, DateTimeKind.Utc).AddTicks(447),
                            Description = "Another admin item with low stock",
                            ExpiryDate = new DateTime(2025, 2, 4, 16, 18, 5, 422, DateTimeKind.Utc).AddTicks(446),
                            ItemName = "Admin Low Stock Item 2",
                            MinimumStockQuantity = 10,
                            Price = 7.99m,
                            StockQuantity = 4,
                            Unit = "pcs",
                            UserId = 1
                        },
                        new
                        {
                            ItemID = 6,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2025, 1, 2, 16, 18, 5, 422, DateTimeKind.Utc).AddTicks(452),
                            Description = "TestUser item nearing expiry",
                            ExpiryDate = new DateTime(2025, 1, 13, 16, 18, 5, 422, DateTimeKind.Utc).AddTicks(451),
                            ItemName = "TestUser Near Expiry Item 1",
                            MinimumStockQuantity = 15,
                            Price = 18.99m,
                            StockQuantity = 25,
                            Unit = "pcs",
                            UserId = 2
                        },
                        new
                        {
                            ItemID = 7,
                            Category = "Office Supplies",
                            CreatedAt = new DateTime(2025, 1, 4, 16, 18, 5, 422, DateTimeKind.Utc).AddTicks(454),
                            Description = "TestUser item with low stock",
                            ExpiryDate = new DateTime(2025, 1, 30, 16, 18, 5, 422, DateTimeKind.Utc).AddTicks(453),
                            ItemName = "TestUser Low Stock Item 1",
                            MinimumStockQuantity = 10,
                            Price = 9.99m,
                            StockQuantity = 2,
                            Unit = "pcs",
                            UserId = 2
                        },
                        new
                        {
                            ItemID = 8,
                            Category = "Food",
                            CreatedAt = new DateTime(2025, 1, 6, 16, 18, 5, 422, DateTimeKind.Utc).AddTicks(458),
                            Description = "TestUser item near expiry and low stock",
                            ExpiryDate = new DateTime(2025, 1, 12, 16, 18, 5, 422, DateTimeKind.Utc).AddTicks(456),
                            ItemName = "TestUser Near Expiry & Low Stock Item",
                            MinimumStockQuantity = 5,
                            Price = 14.99m,
                            StockQuantity = 1,
                            Unit = "boxes",
                            UserId = 2
                        },
                        new
                        {
                            ItemID = 9,
                            Category = "Garden Supplies",
                            CreatedAt = new DateTime(2025, 1, 9, 16, 18, 5, 422, DateTimeKind.Utc).AddTicks(460),
                            Description = "Another TestUser item nearing expiry",
                            ExpiryDate = new DateTime(2025, 1, 17, 16, 18, 5, 422, DateTimeKind.Utc).AddTicks(459),
                            ItemName = "TestUser Near Expiry Item 2",
                            MinimumStockQuantity = 20,
                            Price = 11.99m,
                            StockQuantity = 30,
                            Unit = "pcs",
                            UserId = 2
                        },
                        new
                        {
                            ItemID = 10,
                            Category = "Cleaning Supplies",
                            CreatedAt = new DateTime(2025, 1, 1, 16, 18, 5, 422, DateTimeKind.Utc).AddTicks(462),
                            Description = "Another TestUser item with low stock",
                            ExpiryDate = new DateTime(2025, 2, 1, 16, 18, 5, 422, DateTimeKind.Utc).AddTicks(461),
                            ItemName = "TestUser Low Stock Item 2",
                            MinimumStockQuantity = 10,
                            Price = 8.99m,
                            StockQuantity = 5,
                            Unit = "pcs",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("IMS.DAL.Entities.ItemCategory", b =>
                {
                    b.Property<int>("ItemID")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryID")
                        .HasColumnType("integer");

                    b.HasKey("ItemID", "CategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("ItemCategories");
                });

            modelBuilder.Entity("IMS.DAL.Entities.Stock", b =>
                {
                    b.Property<int>("StockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockID"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemID")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("StockID");

                    b.HasIndex("ItemID");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("IMS.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 10, 16, 18, 5, 303, DateTimeKind.Utc).AddTicks(442),
                            Email = "admin@ims.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$TMjFOWCYwcUK/UvZ4HfuE.ZSPloyfZM8J.CDy71MbAP54pyfUXqZ6",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 10, 16, 18, 5, 420, DateTimeKind.Utc).AddTicks(5925),
                            Email = "test@ims.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$nwt7ZQ8jd7Yioqt6zirY1uc9zlVZAfvVZZYADynjqhk1SXBD1Kpcm",
                            Role = "User",
                            Username = "testuser"
                        });
                });

            modelBuilder.Entity("IMS.DAL.Entities.Item", b =>
                {
                    b.HasOne("IMS.DAL.Entities.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IMS.DAL.Entities.ItemCategory", b =>
                {
                    b.HasOne("IMS.DAL.Entities.Category", "Category")
                        .WithMany("ItemCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMS.DAL.Entities.Item", "Item")
                        .WithMany("ItemCategories")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("IMS.DAL.Entities.Stock", b =>
                {
                    b.HasOne("IMS.DAL.Entities.Item", "Item")
                        .WithMany("Stocks")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("IMS.DAL.Entities.Category", b =>
                {
                    b.Navigation("ItemCategories");
                });

            modelBuilder.Entity("IMS.DAL.Entities.Item", b =>
                {
                    b.Navigation("ItemCategories");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("IMS.DAL.Entities.User", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
