// <auto-generated />
using System;
using IMS.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IMS.DAL.Migrations
{
    [DbContext(typeof(IMSContext))]
    [Migration("20250109094457_AddUserIdToItems")]
    partial class AddUserIdToItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IMS.DAL.Entities.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("IMS.DAL.Entities.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MinimumStockQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ItemID");

                    b.HasIndex("UserId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2025, 1, 8, 9, 44, 56, 951, DateTimeKind.Utc).AddTicks(4433),
                            Description = "Test item with low stock",
                            ExpiryDate = new DateTime(2025, 1, 14, 9, 44, 56, 951, DateTimeKind.Utc).AddTicks(4213),
                            ItemName = "Low Stock Item 1",
                            MinimumStockQuantity = 10,
                            Price = 10.99m,
                            StockQuantity = 5,
                            Unit = "pcs",
                            UserId = 1
                        },
                        new
                        {
                            ItemID = 2,
                            Category = "Office Supplies",
                            CreatedAt = new DateTime(2025, 1, 9, 7, 44, 56, 951, DateTimeKind.Utc).AddTicks(4733),
                            Description = "Recently added item",
                            ExpiryDate = new DateTime(2025, 2, 8, 9, 44, 56, 951, DateTimeKind.Utc).AddTicks(4732),
                            ItemName = "New Item",
                            MinimumStockQuantity = 5,
                            Price = 15.99m,
                            StockQuantity = 20,
                            Unit = "pcs",
                            UserId = 2
                        },
                        new
                        {
                            ItemID = 3,
                            Category = "Food",
                            CreatedAt = new DateTime(2024, 12, 30, 9, 44, 56, 951, DateTimeKind.Utc).AddTicks(4739),
                            Description = "Item near expiry",
                            ExpiryDate = new DateTime(2025, 1, 15, 9, 44, 56, 951, DateTimeKind.Utc).AddTicks(4739),
                            ItemName = "Expiring Item",
                            MinimumStockQuantity = 5,
                            Price = 25.99m,
                            StockQuantity = 15,
                            Unit = "boxes",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("IMS.DAL.Entities.ItemCategory", b =>
                {
                    b.Property<int>("ItemID")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryID")
                        .HasColumnType("integer");

                    b.HasKey("ItemID", "CategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("ItemCategories");
                });

            modelBuilder.Entity("IMS.DAL.Entities.Stock", b =>
                {
                    b.Property<int>("StockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockID"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemID")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("integer");

                    b.HasKey("StockID");

                    b.HasIndex("ItemID");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("IMS.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 9, 9, 44, 56, 853, DateTimeKind.Utc).AddTicks(7621),
                            Email = "admin@ims.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$E160rsbrzKHe9w6VHAN37erwhy/249eG0sWD3gwMd7YRPaM5k9/0u",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 9, 9, 44, 56, 950, DateTimeKind.Utc).AddTicks(7905),
                            Email = "test@ims.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$RrWXU1Qh1qGNeEm/HOHRje6mEHDK1hlnuHg7DbBCJmfUsmZBA04l6",
                            Role = "User",
                            Username = "testuser"
                        });
                });

            modelBuilder.Entity("IMS.DAL.Entities.Item", b =>
                {
                    b.HasOne("IMS.DAL.Entities.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IMS.DAL.Entities.ItemCategory", b =>
                {
                    b.HasOne("IMS.DAL.Entities.Category", "Category")
                        .WithMany("ItemCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMS.DAL.Entities.Item", "Item")
                        .WithMany("ItemCategories")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("IMS.DAL.Entities.Stock", b =>
                {
                    b.HasOne("IMS.DAL.Entities.Item", "Item")
                        .WithMany("Stocks")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("IMS.DAL.Entities.Category", b =>
                {
                    b.Navigation("ItemCategories");
                });

            modelBuilder.Entity("IMS.DAL.Entities.Item", b =>
                {
                    b.Navigation("ItemCategories");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("IMS.DAL.Entities.User", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
