// <auto-generated />
using System;
using IMS.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IMS.DAL.Migrations
{
    [DbContext(typeof(IMSContext))]
    partial class IMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IMS.DAL.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Electronics",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Office Supplies",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Food",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Garden Supplies",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Cleaning Supplies",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Electronics",
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Office Supplies",
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Food",
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Garden Supplies",
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "Cleaning Supplies",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("IMS.DAL.Entities.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ItemID");

                    b.HasIndex("UserId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            CreatedAt = new DateTime(2025, 1, 5, 18, 42, 10, 563, DateTimeKind.Utc).AddTicks(3431),
                            Description = "Admin item nearing expiry",
                            Name = "Admin Near Expiry Item 1",
                            Price = 20.99m,
                            Unit = "pcs",
                            UserId = 1
                        },
                        new
                        {
                            ItemID = 2,
                            CreatedAt = new DateTime(2025, 1, 10, 18, 42, 10, 563, DateTimeKind.Utc).AddTicks(3671),
                            Description = "Admin item with low stock",
                            Name = "Admin Low Stock Item 1",
                            Price = 5.99m,
                            Unit = "pcs",
                            UserId = 1
                        },
                        new
                        {
                            ItemID = 3,
                            CreatedAt = new DateTime(2025, 1, 8, 18, 42, 10, 563, DateTimeKind.Utc).AddTicks(3674),
                            Description = "Admin item near expiry and low stock",
                            Name = "Admin Near Expiry & Low Stock Item",
                            Price = 15.99m,
                            Unit = "boxes",
                            UserId = 1
                        },
                        new
                        {
                            ItemID = 4,
                            CreatedAt = new DateTime(2025, 1, 13, 18, 42, 10, 563, DateTimeKind.Utc).AddTicks(3675),
                            Description = "Another admin item nearing expiry",
                            Name = "Admin Near Expiry Item 2",
                            Price = 12.99m,
                            Unit = "pcs",
                            UserId = 1
                        },
                        new
                        {
                            ItemID = 5,
                            CreatedAt = new DateTime(2025, 1, 12, 18, 42, 10, 563, DateTimeKind.Utc).AddTicks(3677),
                            Description = "Another admin item with low stock",
                            Name = "Admin Low Stock Item 2",
                            Price = 7.99m,
                            Unit = "pcs",
                            UserId = 1
                        },
                        new
                        {
                            ItemID = 6,
                            CreatedAt = new DateTime(2025, 1, 7, 18, 42, 10, 563, DateTimeKind.Utc).AddTicks(3789),
                            Description = "TestUser item nearing expiry",
                            Name = "TestUser Near Expiry Item 1",
                            Price = 18.99m,
                            Unit = "pcs",
                            UserId = 2
                        },
                        new
                        {
                            ItemID = 7,
                            CreatedAt = new DateTime(2025, 1, 9, 18, 42, 10, 563, DateTimeKind.Utc).AddTicks(3791),
                            Description = "TestUser item with low stock",
                            Name = "TestUser Low Stock Item 1",
                            Price = 9.99m,
                            Unit = "pcs",
                            UserId = 2
                        },
                        new
                        {
                            ItemID = 8,
                            CreatedAt = new DateTime(2025, 1, 11, 18, 42, 10, 563, DateTimeKind.Utc).AddTicks(3792),
                            Description = "TestUser item near expiry and low stock",
                            Name = "TestUser Near Expiry & Low Stock Item",
                            Price = 14.99m,
                            Unit = "boxes",
                            UserId = 2
                        },
                        new
                        {
                            ItemID = 9,
                            CreatedAt = new DateTime(2025, 1, 14, 18, 42, 10, 563, DateTimeKind.Utc).AddTicks(3793),
                            Description = "Another TestUser item nearing expiry",
                            Name = "TestUser Near Expiry Item 2",
                            Price = 11.99m,
                            Unit = "pcs",
                            UserId = 2
                        },
                        new
                        {
                            ItemID = 10,
                            CreatedAt = new DateTime(2025, 1, 6, 18, 42, 10, 563, DateTimeKind.Utc).AddTicks(3794),
                            Description = "Another TestUser item with low stock",
                            Name = "TestUser Low Stock Item 2",
                            Price = 8.99m,
                            Unit = "pcs",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("IMS.DAL.Entities.ItemCategory", b =>
                {
                    b.Property<int>("ItemID")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryID")
                        .HasColumnType("integer");

                    b.HasKey("ItemID", "CategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("ItemCategories");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            CategoryID = 1
                        },
                        new
                        {
                            ItemID = 2,
                            CategoryID = 2
                        },
                        new
                        {
                            ItemID = 3,
                            CategoryID = 3
                        },
                        new
                        {
                            ItemID = 4,
                            CategoryID = 4
                        },
                        new
                        {
                            ItemID = 5,
                            CategoryID = 5
                        },
                        new
                        {
                            ItemID = 6,
                            CategoryID = 6
                        },
                        new
                        {
                            ItemID = 7,
                            CategoryID = 7
                        },
                        new
                        {
                            ItemID = 8,
                            CategoryID = 8
                        },
                        new
                        {
                            ItemID = 9,
                            CategoryID = 9
                        },
                        new
                        {
                            ItemID = 10,
                            CategoryID = 10
                        });
                });

            modelBuilder.Entity("IMS.DAL.Entities.Stock", b =>
                {
                    b.Property<int>("StockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockID"));

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemID")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("StockID");

                    b.HasIndex("ItemID");

                    b.HasIndex("UserId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("IMS.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 15, 18, 42, 10, 468, DateTimeKind.Utc).AddTicks(1946),
                            Email = "admin@ims.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$YOzrIlrUGgBtKNpGOn51L.StP88zt834xrF3LYwebiQPsZYKC2vp2",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 15, 18, 42, 10, 562, DateTimeKind.Utc).AddTicks(6706),
                            Email = "test@ims.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$jrqr3zR/WdxMA8yaxTExy.e5OLPbRmbOpIfNWglSSVLq3YFdrOte.",
                            Role = "User",
                            Username = "testuser"
                        });
                });

            modelBuilder.Entity("IMS.DAL.Entities.Category", b =>
                {
                    b.HasOne("IMS.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IMS.DAL.Entities.Item", b =>
                {
                    b.HasOne("IMS.DAL.Entities.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IMS.DAL.Entities.ItemCategory", b =>
                {
                    b.HasOne("IMS.DAL.Entities.Category", "Category")
                        .WithMany("ItemCategory")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMS.DAL.Entities.Item", "Item")
                        .WithMany("ItemCategory")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("IMS.DAL.Entities.Stock", b =>
                {
                    b.HasOne("IMS.DAL.Entities.Item", "Item")
                        .WithMany("Stocks")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMS.DAL.Entities.User", "User")
                        .WithMany("Stocks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IMS.DAL.Entities.Category", b =>
                {
                    b.Navigation("ItemCategory");
                });

            modelBuilder.Entity("IMS.DAL.Entities.Item", b =>
                {
                    b.Navigation("ItemCategory");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("IMS.DAL.Entities.User", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
