version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: windows
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    networks:
      - sql-network
    healthcheck:
      test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Passw0rd", "-Q", "SELECT 1"]
      interval: 10s
      retries: 10
      timeout: 3s

networks:
  sql-network:
    driver: nat