services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONFIGURATION=Release
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=ims-postgres-server.postgres.database.azure.com;Port=5432;Database=ims_db;Username=postgres@ims-postgres-server;Password=Watchdogs1!;SSL Mode=Require;Trust Server Certificate=True
    restart: always