@startuml
class DesignTimeDbContextFactory {
    + CreateDbContext(args:string[]) : IMSContext
}
class "IDesignTimeDbContextFactory`1"<T> {
}
"IDesignTimeDbContextFactory`1" "<IMSContext>" <|-- DesignTimeDbContextFactory
@enduml
