@startuml
!include .\\IMS.API\Program.puml
!include .\\IMS.DAL\DesignTimeDbContextFactory.puml
!include .\\IMS.DAL\IMSContext.puml
!include .\\IMSTests\AuthControllerIntegrationTests.puml
!include .\\IMS.API\Controllers\AdminController.puml
!include .\\IMS.API\Controllers\AuthController.puml
!include .\\IMS.API\Controllers\ClientDashboardController.puml
!include .\\IMS.API\Controllers\InventoryController.puml
!include .\\IMS.API\Middleware\ExceptionMiddleware.puml
!include .\\IMS.API\ViewModels\CategoryViewModel.puml
!include .\\IMS.API\ViewModels\ItemCategoryViewModel.puml
!include .\\IMS.API\ViewModels\ItemViewModel.puml
!include .\\IMS.API\ViewModels\StockViewModel.puml
!include .\\IMS.BLL\Exceptions\AuthException.puml
!include .\\IMS.BLL\Models\CategoryModel.puml
!include .\\IMS.BLL\Models\ItemCategoryModel.puml
!include .\\IMS.BLL\Models\ItemModel.puml
!include .\\IMS.BLL\Models\StockModel.puml
!include .\\IMS.BLL\Services\AuthService.puml
!include .\\IMS.BLL\Services\ClientDashboardService.puml
!include .\\IMS.BLL\Services\InventoryService.puml
!include .\\IMS.BLL\Services\JwtService.puml
!include .\\IMS.DAL\Entities\Category.puml
!include .\\IMS.DAL\Entities\Item.puml
!include .\\IMS.DAL\Entities\ItemCategory.puml
!include .\\IMS.DAL\Entities\Stock.puml
!include .\\IMS.DAL\Entities\User.puml
!include .\\IMS.DAL\Mapping\AutoMapperProfile.puml
!include .\\IMS.DAL\Migrations\20241227183959_InitialCreate.puml
!include .\\IMS.DAL\Migrations\20241227183959_InitialCreate.Designer.puml
!include .\\IMS.DAL\Migrations\20241227195156_AddTestColumn.puml
!include .\\IMS.DAL\Migrations\20241227195156_AddTestColumn.Designer.puml
!include .\\IMS.DAL\Migrations\20241227200348_AddItemDescription.puml
!include .\\IMS.DAL\Migrations\20241227200348_AddItemDescription.Designer.puml
!include .\\IMS.DAL\Migrations\20241227204349_AddTestUser.puml
!include .\\IMS.DAL\Migrations\20241227204349_AddTestUser.Designer.puml
!include .\\IMS.DAL\Migrations\20250108182150_AddItemSeedData.puml
!include .\\IMS.DAL\Migrations\20250108182150_AddItemSeedData.Designer.puml
!include .\\IMS.DAL\Migrations\20250108195653_AddcorrectedItemSeedData.puml
!include .\\IMS.DAL\Migrations\20250108195653_AddcorrectedItemSeedData.Designer.puml
!include .\\IMS.DAL\Migrations\20250109085815_AddIdToDashboardDTOs.puml
!include .\\IMS.DAL\Migrations\20250109085815_AddIdToDashboardDTOs.Designer.puml
!include .\\IMS.DAL\Migrations\20250109094457_AddUserIdToItems.puml
!include .\\IMS.DAL\Migrations\20250109094457_AddUserIdToItems.Designer.puml
!include .\\IMS.DAL\Migrations\20250109101440_AddMoreTestingItems.puml
!include .\\IMS.DAL\Migrations\20250109101440_AddMoreTestingItems.Designer.puml
!include .\\IMS.DAL\Migrations\20250109113932_Inventoryupdate.puml
!include .\\IMS.DAL\Migrations\20250109113932_Inventoryupdate.Designer.puml
!include .\\IMS.DAL\Migrations\20250110161805_UpdateInventoryRepository.puml
!include .\\IMS.DAL\Migrations\20250110161805_UpdateInventoryRepository.Designer.puml
!include .\\IMS.DAL\Migrations\20250111115209_UpdateInventoryEntitiesAndDTOs.puml
!include .\\IMS.DAL\Migrations\20250111115209_UpdateInventoryEntitiesAndDTOs.Designer.puml
!include .\\IMS.DAL\Migrations\20250112121237_UpdateItemandStock.puml
!include .\\IMS.DAL\Migrations\20250112121237_UpdateItemandStock.Designer.puml
!include .\\IMS.DAL\Migrations\20250113200401_MigrationName.puml
!include .\\IMS.DAL\Migrations\20250113200401_MigrationName.Designer.puml
!include .\\IMS.DAL\Migrations\20250113204336_ITEMMIGRATIONTEST.puml
!include .\\IMS.DAL\Migrations\20250113204336_ITEMMIGRATIONTEST.Designer.puml
!include .\\IMS.DAL\Migrations\20250115183621_AddUserIdToStock.puml
!include .\\IMS.DAL\Migrations\20250115183621_AddUserIdToStock.Designer.puml
!include .\\IMS.DAL\Migrations\20250115184210_AddUserIdToStockAndRelation.puml
!include .\\IMS.DAL\Migrations\20250115184210_AddUserIdToStockAndRelation.Designer.puml
!include .\\IMS.DAL\Migrations\IMSContextModelSnapshot.puml
!include .\\IMS.DAL\Repositories\AuthRepository.puml
!include .\\IMS.DAL\Repositories\InventoryRepository.puml
!include .\\IMSTests\Services\CategoriesServiceTests.puml
!include .\\IMSTests\Services\ItemServiceTests.puml
!include .\\IMSTests\Services\StockServiceTest.puml
!include .\\IMS.BLL\DTOs\Admin\AdminDashboardStatsDTO.puml
!include .\\IMS.BLL\DTOs\Auth\AdminUserDTO.puml
!include .\\IMS.BLL\DTOs\Auth\LoginDTO.puml
!include .\\IMS.BLL\DTOs\Auth\RegisterDTO.puml
!include .\\IMS.BLL\DTOs\Auth\UpdateUserDTO.puml
!include .\\IMS.BLL\DTOs\Auth\UserDTO.puml
!include .\\IMS.BLL\DTOs\ClientDashboard\ClientDashboardStatsDTO.puml
!include .\\IMS.BLL\DTOs\Inventory\CategoryDTO.puml
!include .\\IMS.BLL\DTOs\Inventory\CreateCategoryDTO.puml
!include .\\IMS.BLL\DTOs\Inventory\ItemDTO.puml
!include .\\IMS.BLL\DTOs\Inventory\StockDTO.puml
!include .\\IMS.BLL\DTOs\Inventory\UpdateCategoryDTO.puml
!include .\\IMS.BLL\DTOs\Inventory\UpdateItemDTO.puml
!include .\\IMS.BLL\DTOs\Inventory\UpdateStockDTO.puml
!include .\\IMS.BLL\Interfaces\Repositories\IAuthRepository.puml
!include .\\IMS.BLL\Interfaces\Repositories\IClientDashboardRepository.puml
!include .\\IMS.BLL\Interfaces\Repositories\IInventoryRepository.puml
!include .\\IMS.BLL\Interfaces\Services\IAuthService.puml
!include .\\IMS.BLL\Interfaces\Services\IClientDashboardService.puml
!include .\\IMS.BLL\Interfaces\Services\IInventoryService.puml
!include .\\IMS.API\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\IMS.API\obj\Debug\net8.0\IMS.API.AssemblyInfo.puml
!include .\\IMS.API\obj\Debug\net8.0\IMS.API.GlobalUsings.g.puml
!include .\\IMS.API\obj\Debug\net8.0\IMS.API.MvcApplicationPartsAssemblyInfo.puml
!include .\\IMS.API\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\IMS.API\obj\Release\net8.0\IMS.API.AssemblyInfo.puml
!include .\\IMS.API\obj\Release\net8.0\IMS.API.GlobalUsings.g.puml
!include .\\IMS.BLL\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\IMS.BLL\obj\Debug\net8.0\IMS.BLL.AssemblyInfo.puml
!include .\\IMS.BLL\obj\Debug\net8.0\IMS.BLL.GlobalUsings.g.puml
!include .\\IMS.BLL\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\IMS.BLL\obj\Release\net8.0\IMS.BLL.AssemblyInfo.puml
!include .\\IMS.BLL\obj\Release\net8.0\IMS.BLL.GlobalUsings.g.puml
!include .\\IMS.DAL\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\IMS.DAL\obj\Debug\net8.0\IMS.DAL.AssemblyInfo.puml
!include .\\IMS.DAL\obj\Debug\net8.0\IMS.DAL.GlobalUsings.g.puml
!include .\\IMS.DAL\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\IMS.DAL\obj\Release\net8.0\IMS.DAL.AssemblyInfo.puml
!include .\\IMS.DAL\obj\Release\net8.0\IMS.DAL.GlobalUsings.g.puml
!include .\\IMSTests\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\IMSTests\obj\Debug\net8.0\IMSTests.AssemblyInfo.puml
!include .\\IMSTests\obj\Debug\net8.0\IMSTests.GlobalUsings.g.puml
!include .\\IMSTests\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\IMSTests\obj\Release\net8.0\IMSTests.AssemblyInfo.puml
!include .\\IMSTests\obj\Release\net8.0\IMSTests.GlobalUsings.g.puml
@enduml
