name: IMS CI/CD Pipeline

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Debug Branch Info
      run: |
        echo "Current branch: ${{ github.ref }}"
        echo "Is main branch? ${{ github.ref == 'refs/heads/main' }}"
    
    - name: Setup SQL Server Express
      shell: pwsh
      run: |
        choco install sql-server-express -y --params="'/INSTANCENAME:SQLEXPRESS'"
        Start-Sleep -s 30
        Get-Service -Name *SQL* | Format-Table Name, Status
        Start-Service -Name "MSSQL`$SQLEXPRESS"
        Start-Sleep -s 10
        sqlcmd -S "(local)\SQLEXPRESS" -Q "CREATE DATABASE IMS_Test"
    
    - name: Run Tests
      run: |
        dotnet restore
        dotnet build --configuration Debug
        dotnet test --configuration Debug --no-build
      env:
        ConnectionStrings__DefaultConnection: Server=(local)\SQLEXPRESS;Database=IMS_Test;Trusted_Connection=True;TrustServerCertificate=True

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
      
    - name: Build Docker Images
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Building Docker images..."
        docker-compose -f docker-compose.prod.yml build --progress=plain