name: IMS CI/CD Pipeline

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Start Dev SQL Server
      shell: pwsh
      run: |
        # Use Windows SQL Server image instead of Linux
        docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=YourStrong@Passw0rd" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest-windows
        Start-Sleep -s 30  # Wait for SQL Server to start
    
    - name: Run Tests
      run: |
        dotnet restore
        dotnet build --configuration Debug
        dotnet test --configuration Debug --no-build
      env:
        ConnectionStrings__DefaultConnection: Server=.,1433;Database=IMS_Test;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
    
  deploy-production:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    
    - name: Build and Push Docker Images
      run: |
        docker-compose -f docker-compose.prod.yml build
        docker-compose -f docker-compose.prod.yml push