name: IMS CI/CD Pipeline

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Start Dev SQL Server
      shell: pwsh
      run: |
        docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=YourStrong@Passw0rd" -p 1433:1433 -d mcr.microsoft.com/azure-sql-edge
        Start-Sleep -s 30  # Wait for SQL Server to start
        
        # Verify SQL Server is running
        docker ps
        
        # Test connection
        $retry = 5
        do {
            $retry--
            try {
                docker exec $(docker ps -q) /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong@Passw0rd" -Q "SELECT @@VERSION"
                break
            } catch {
                Start-Sleep -s 10
            }
        } while ($retry -gt 0)
    
    - name: Run Tests
      run: |
        dotnet restore
        dotnet build --configuration Debug
        dotnet test --configuration Debug --no-build
      env:
        ConnectionStrings__DefaultConnection: Server=localhost,1433;Database=IMS_Test;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True

    - name: Build Docker Images
      if: github.ref == 'refs/heads/main'
      run: |
        docker-compose -f docker-compose.prod.yml build